import monaco from "monaco-editor";

export const EditorThemes: Record<
  string,
  { name: string; definition: monaco.editor.IStandaloneThemeData }
> = {
  // ===========================================================================
  // Invert IDE App Themes
  // ===========================================================================
  "Invert Dark": {
    name: "invert-dark",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "0a0a0c", foreground: "f0f0f0" },
        { token: "keyword", foreground: "da70d6", fontStyle: "bold" },
        { token: "keyword.control", foreground: "da70d6" },
        { token: "type", foreground: "4ec9b0" },
        { token: "type.identifier", foreground: "4ec9b0" },
        { token: "string", foreground: "ce9178" },
        { token: "string.escape", foreground: "ffba00" },
        { token: "comment", foreground: "808080", fontStyle: "italic" },
        { token: "function", foreground: "dcdcaa" },
        { token: "variable", foreground: "9cdcfe" },
        { token: "variable.parameter", foreground: "9cdcfe" },
        { token: "number", foreground: "b5cea8" },
        { token: "constant", foreground: "569cd6" },
        { token: "operator", foreground: "f0f0f0" },
        { token: "delimiter", foreground: "808080" },
        { token: "tag", foreground: "569cd6" },
        { token: "attribute.name", foreground: "9cdcfe" },
        { token: "attribute.value", foreground: "ce9178" },
      ],
      colors: {
        "editor.background": "#0a0a0c",
        "editor.foreground": "#f0f0f0",
        "editorLineNumber.foreground": "#808080",
        "editorLineNumber.activeForeground": "#f0f0f0",
        "editorCursor.foreground": "#ffba00",
        "editor.selectionBackground": "#1868c466",
        "editor.inactiveSelectionBackground": "#1868c433",
        "editorIndentGuide.background1": "#2d2d2d",
        "editorIndentGuide.activeBackground1": "#808080",
        "editor.lineHighlightBackground": "#1e1e1e",
        "editorBracketMatch.background": "#1868c433",
        "editorBracketMatch.border": "#1868c4",
      },
    },
  },

  // ===========================================================================
  // Visual Studio Code Themes
  // ===========================================================================
  "VS Code Dark": {
    name: "vscode-dark",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "1e1e1e", foreground: "d4d4d4" },
        { token: "keyword", foreground: "569cd6" },
        { token: "keyword.control", foreground: "c586c0" },
        { token: "type", foreground: "4ec9b0" },
        { token: "string", foreground: "ce9178" },
        { token: "comment", foreground: "6a9955", fontStyle: "italic" },
        { token: "function", foreground: "dcdcaa" },
        { token: "variable", foreground: "9cdcfe" },
        { token: "number", foreground: "b5cea8" },
        { token: "constant", foreground: "4fc1ff" },
        { token: "operator", foreground: "d4d4d4" },
        { token: "delimiter", foreground: "808080" },
      ],
      colors: {
        "editor.background": "#1e1e1e",
        "editor.foreground": "#d4d4d4",
        "editorLineNumber.foreground": "#858585",
        "editorLineNumber.activeForeground": "#c6c6c6",
        "editorCursor.foreground": "#aeafad",
        "editor.selectionBackground": "#264f78",
        "editor.inactiveSelectionBackground": "#3a3d41",
        "editorIndentGuide.background1": "#404040",
        "editorIndentGuide.activeBackground1": "#707070",
        "editor.lineHighlightBackground": "#2a2d2e",
        "editorBracketMatch.background": "#0064001a",
        "editorBracketMatch.border": "#888888",
      },
    },
  },
  "VS Code Dark+": {
    name: "vscode-dark-plus",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "1e1e1e", foreground: "d4d4d4" },
        { token: "keyword", foreground: "569cd6", fontStyle: "bold" },
        { token: "keyword.control", foreground: "c586c0" },
        { token: "type", foreground: "4ec9b0" },
        { token: "type.identifier", foreground: "4ec9b0" },
        { token: "string", foreground: "ce9178" },
        { token: "string.escape", foreground: "d7ba7d" },
        { token: "comment", foreground: "6a9955", fontStyle: "italic" },
        { token: "function", foreground: "dcdcaa" },
        { token: "variable", foreground: "9cdcfe" },
        { token: "variable.parameter", foreground: "9cdcfe" },
        { token: "number", foreground: "b5cea8" },
        { token: "constant", foreground: "4fc1ff" },
        { token: "operator", foreground: "d4d4d4" },
        { token: "delimiter", foreground: "808080" },
        { token: "tag", foreground: "569cd6" },
        { token: "attribute.name", foreground: "9cdcfe" },
        { token: "attribute.value", foreground: "ce9178" },
      ],
      colors: {
        "editor.background": "#1e1e1e",
        "editor.foreground": "#d4d4d4",
        "editorLineNumber.foreground": "#858585",
        "editorLineNumber.activeForeground": "#c6c6c6",
        "editorCursor.foreground": "#aeafad",
        "editor.selectionBackground": "#264f78",
        "editor.inactiveSelectionBackground": "#3a3d41",
        "editorIndentGuide.background1": "#404040",
        "editorIndentGuide.activeBackground1": "#707070",
        "editor.lineHighlightBackground": "#2a2d2e",
        "editorBracketMatch.background": "#0064001a",
        "editorBracketMatch.border": "#888888",
      },
    },
  },
  "VS Code Dark Modern": {
    name: "vscode-dark-modern",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "1f1f1f", foreground: "cccccc" },
        { token: "keyword", foreground: "569cd6" },
        { token: "keyword.control", foreground: "c586c0" },
        { token: "type", foreground: "4ec9b0" },
        { token: "type.identifier", foreground: "4ec9b0" },
        { token: "string", foreground: "ce9178" },
        { token: "string.escape", foreground: "d7ba7d" },
        { token: "comment", foreground: "6a9955", fontStyle: "italic" },
        { token: "function", foreground: "dcdcaa" },
        { token: "variable", foreground: "9cdcfe" },
        { token: "variable.parameter", foreground: "9cdcfe" },
        { token: "number", foreground: "b5cea8" },
        { token: "constant", foreground: "4fc1ff" },
        { token: "operator", foreground: "cccccc" },
        { token: "delimiter", foreground: "808080" },
        { token: "tag", foreground: "569cd6" },
        { token: "attribute.name", foreground: "9cdcfe" },
        { token: "attribute.value", foreground: "ce9178" },
      ],
      colors: {
        "editor.background": "#1f1f1f",
        "editor.foreground": "#cccccc",
        "editorLineNumber.foreground": "#6e7681",
        "editorLineNumber.activeForeground": "#cccccc",
        "editorCursor.foreground": "#aeafad",
        "editor.selectionBackground": "#264f78",
        "editor.inactiveSelectionBackground": "#3a3d41",
        "editorIndentGuide.background1": "#404040",
        "editorIndentGuide.activeBackground1": "#707070",
        "editor.lineHighlightBackground": "#2a2d2e",
        "editorBracketMatch.background": "#0064001a",
        "editorBracketMatch.border": "#888888",
      },
    },
  },

  // ===========================================================================
  // Material Themes
  // ===========================================================================
  "Material Darker": {
    name: "material-darker",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "212121", foreground: "eeffff" },
        { token: "keyword", foreground: "c792ea", fontStyle: "bold" },
        { token: "keyword.control", foreground: "c792ea" },
        { token: "type", foreground: "ffcb6b" },
        { token: "type.identifier", foreground: "ffcb6b" },
        { token: "string", foreground: "c3e88d" },
        { token: "string.escape", foreground: "89ddff" },
        { token: "comment", foreground: "545454", fontStyle: "italic" },
        { token: "function", foreground: "82aaff" },
        { token: "variable", foreground: "eeffff" },
        { token: "variable.parameter", foreground: "f78c6c" },
        { token: "number", foreground: "f78c6c" },
        { token: "constant", foreground: "f78c6c" },
        { token: "operator", foreground: "89ddff" },
        { token: "delimiter", foreground: "89ddff" },
        { token: "tag", foreground: "f07178" },
        { token: "attribute.name", foreground: "ffcb6b" },
        { token: "attribute.value", foreground: "c3e88d" },
      ],
      colors: {
        "editor.background": "#212121",
        "editor.foreground": "#eeffff",
        "editorLineNumber.foreground": "#424242",
        "editorLineNumber.activeForeground": "#89ddff",
        "editorCursor.foreground": "#ffcc00",
        "editor.selectionBackground": "#61616150",
        "editor.inactiveSelectionBackground": "#42424240",
        "editorIndentGuide.background1": "#424242",
        "editorIndentGuide.activeBackground1": "#616161",
        "editor.lineHighlightBackground": "#2a2a2a",
        "editorBracketMatch.background": "#61616150",
        "editorBracketMatch.border": "#ffcc00",
      },
    },
  },
  "Material Ocean": {
    name: "material-ocean",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "0f111a", foreground: "8f93a2" },
        { token: "keyword", foreground: "c792ea", fontStyle: "bold" },
        { token: "keyword.control", foreground: "c792ea" },
        { token: "type", foreground: "ffcb6b" },
        { token: "type.identifier", foreground: "ffcb6b" },
        { token: "string", foreground: "c3e88d" },
        { token: "string.escape", foreground: "89ddff" },
        { token: "comment", foreground: "464b5d", fontStyle: "italic" },
        { token: "function", foreground: "82aaff" },
        { token: "variable", foreground: "8f93a2" },
        { token: "variable.parameter", foreground: "f78c6c" },
        { token: "number", foreground: "f78c6c" },
        { token: "constant", foreground: "f78c6c" },
        { token: "operator", foreground: "89ddff" },
        { token: "delimiter", foreground: "89ddff" },
        { token: "tag", foreground: "f07178" },
        { token: "attribute.name", foreground: "ffcb6b" },
        { token: "attribute.value", foreground: "c3e88d" },
      ],
      colors: {
        "editor.background": "#0f111a",
        "editor.foreground": "#8f93a2",
        "editorLineNumber.foreground": "#3b3f51",
        "editorLineNumber.activeForeground": "#84ffff",
        "editorCursor.foreground": "#ffcc00",
        "editor.selectionBackground": "#717cb450",
        "editor.inactiveSelectionBackground": "#717cb430",
        "editorIndentGuide.background1": "#3b3f51",
        "editorIndentGuide.activeBackground1": "#4b526d",
        "editor.lineHighlightBackground": "#0f111a",
        "editorBracketMatch.background": "#717cb450",
        "editorBracketMatch.border": "#ffcc00",
      },
    },
  },
  "Material Palenight": {
    name: "material-palenight",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "292d3e", foreground: "a6accd" },
        { token: "keyword", foreground: "c792ea", fontStyle: "bold" },
        { token: "keyword.control", foreground: "c792ea" },
        { token: "type", foreground: "ffcb6b" },
        { token: "type.identifier", foreground: "ffcb6b" },
        { token: "string", foreground: "c3e88d" },
        { token: "string.escape", foreground: "89ddff" },
        { token: "comment", foreground: "676e95", fontStyle: "italic" },
        { token: "function", foreground: "82aaff" },
        { token: "variable", foreground: "a6accd" },
        { token: "variable.parameter", foreground: "f78c6c" },
        { token: "number", foreground: "f78c6c" },
        { token: "constant", foreground: "f78c6c" },
        { token: "operator", foreground: "89ddff" },
        { token: "delimiter", foreground: "89ddff" },
        { token: "tag", foreground: "f07178" },
        { token: "attribute.name", foreground: "ffcb6b" },
        { token: "attribute.value", foreground: "c3e88d" },
      ],
      colors: {
        "editor.background": "#292d3e",
        "editor.foreground": "#a6accd",
        "editorLineNumber.foreground": "#3a3f58",
        "editorLineNumber.activeForeground": "#ffcb6b",
        "editorCursor.foreground": "#ffcc00",
        "editor.selectionBackground": "#717cb450",
        "editor.inactiveSelectionBackground": "#717cb430",
        "editorIndentGuide.background1": "#3a3f58",
        "editorIndentGuide.activeBackground1": "#4e5579",
        "editor.lineHighlightBackground": "#2f3344",
        "editorBracketMatch.background": "#717cb450",
        "editorBracketMatch.border": "#ffcc00",
      },
    },
  },

  // ===========================================================================
  // GitHub Themes
  // ===========================================================================
  "GitHub Dark": {
    name: "github-dark",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "0d1117", foreground: "c9d1d9" },
        { token: "keyword", foreground: "ff7b72" },
        { token: "keyword.control", foreground: "ff7b72" },
        { token: "type", foreground: "ffa657" },
        { token: "type.identifier", foreground: "ffa657" },
        { token: "string", foreground: "a5d6ff" },
        { token: "string.escape", foreground: "79c0ff" },
        { token: "comment", foreground: "8b949e", fontStyle: "italic" },
        { token: "function", foreground: "d2a8ff" },
        { token: "variable", foreground: "c9d1d9" },
        { token: "variable.parameter", foreground: "ffa657" },
        { token: "number", foreground: "79c0ff" },
        { token: "constant", foreground: "79c0ff" },
        { token: "operator", foreground: "ff7b72" },
        { token: "delimiter", foreground: "c9d1d9" },
        { token: "tag", foreground: "7ee787" },
        { token: "attribute.name", foreground: "79c0ff" },
        { token: "attribute.value", foreground: "a5d6ff" },
      ],
      colors: {
        "editor.background": "#0d1117",
        "editor.foreground": "#c9d1d9",
        "editorLineNumber.foreground": "#6e7681",
        "editorLineNumber.activeForeground": "#c9d1d9",
        "editorCursor.foreground": "#58a6ff",
        "editor.selectionBackground": "#264f7866",
        "editor.inactiveSelectionBackground": "#264f7844",
        "editorIndentGuide.background1": "#21262d",
        "editorIndentGuide.activeBackground1": "#30363d",
        "editor.lineHighlightBackground": "#161b22",
        "editorBracketMatch.background": "#264f7866",
        "editorBracketMatch.border": "#58a6ff",
      },
    },
  },
  "GitHub Dark Dimmed": {
    name: "github-dark-dimmed",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "22272e", foreground: "adbac7" },
        { token: "keyword", foreground: "f47067" },
        { token: "keyword.control", foreground: "f47067" },
        { token: "type", foreground: "f69d50" },
        { token: "type.identifier", foreground: "f69d50" },
        { token: "string", foreground: "96d0ff" },
        { token: "string.escape", foreground: "6cb6ff" },
        { token: "comment", foreground: "768390", fontStyle: "italic" },
        { token: "function", foreground: "dcbdfb" },
        { token: "variable", foreground: "adbac7" },
        { token: "variable.parameter", foreground: "f69d50" },
        { token: "number", foreground: "6cb6ff" },
        { token: "constant", foreground: "6cb6ff" },
        { token: "operator", foreground: "f47067" },
        { token: "delimiter", foreground: "adbac7" },
        { token: "tag", foreground: "8ddb8c" },
        { token: "attribute.name", foreground: "6cb6ff" },
        { token: "attribute.value", foreground: "96d0ff" },
      ],
      colors: {
        "editor.background": "#22272e",
        "editor.foreground": "#adbac7",
        "editorLineNumber.foreground": "#636e7b",
        "editorLineNumber.activeForeground": "#adbac7",
        "editorCursor.foreground": "#539bf5",
        "editor.selectionBackground": "#3d6b9866",
        "editor.inactiveSelectionBackground": "#3d6b9844",
        "editorIndentGuide.background1": "#2d333b",
        "editorIndentGuide.activeBackground1": "#373e47",
        "editor.lineHighlightBackground": "#2d333b",
        "editorBracketMatch.background": "#3d6b9866",
        "editorBracketMatch.border": "#539bf5",
      },
    },
  },
  "GitHub Light": {
    name: "github-light",
    definition: {
      base: "vs",
      inherit: true,
      rules: [
        { token: "", background: "ffffff", foreground: "24292f" },
        { token: "keyword", foreground: "cf222e" },
        { token: "keyword.control", foreground: "cf222e" },
        { token: "type", foreground: "953800" },
        { token: "type.identifier", foreground: "953800" },
        { token: "string", foreground: "0a3069" },
        { token: "string.escape", foreground: "0550ae" },
        { token: "comment", foreground: "6e7781", fontStyle: "italic" },
        { token: "function", foreground: "8250df" },
        { token: "variable", foreground: "24292f" },
        { token: "variable.parameter", foreground: "953800" },
        { token: "number", foreground: "0550ae" },
        { token: "constant", foreground: "0550ae" },
        { token: "operator", foreground: "cf222e" },
        { token: "delimiter", foreground: "24292f" },
        { token: "tag", foreground: "116329" },
        { token: "attribute.name", foreground: "0550ae" },
        { token: "attribute.value", foreground: "0a3069" },
      ],
      colors: {
        "editor.background": "#ffffff",
        "editor.foreground": "#24292f",
        "editorLineNumber.foreground": "#8c959f",
        "editorLineNumber.activeForeground": "#24292f",
        "editorCursor.foreground": "#0969da",
        "editor.selectionBackground": "#0969da33",
        "editor.inactiveSelectionBackground": "#0969da22",
        "editorIndentGuide.background1": "#d0d7de",
        "editorIndentGuide.activeBackground1": "#afb8c1",
        "editor.lineHighlightBackground": "#f6f8fa",
        "editorBracketMatch.background": "#0969da33",
        "editorBracketMatch.border": "#0969da",
      },
    },
  },

  // ===========================================================================
  // Monokai
  // ===========================================================================
  Monokai: {
    name: "monokai",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "272822", foreground: "f8f8f2" },
        { token: "keyword", foreground: "f92672" },
        { token: "keyword.control", foreground: "f92672" },
        { token: "type", foreground: "66d9ef", fontStyle: "italic" },
        { token: "type.identifier", foreground: "a6e22e" },
        { token: "string", foreground: "e6db74" },
        { token: "string.escape", foreground: "ae81ff" },
        { token: "comment", foreground: "88846f", fontStyle: "italic" },
        { token: "function", foreground: "a6e22e" },
        { token: "variable", foreground: "f8f8f2" },
        { token: "variable.parameter", foreground: "fd971f", fontStyle: "italic" },
        { token: "number", foreground: "ae81ff" },
        { token: "constant", foreground: "ae81ff" },
        { token: "operator", foreground: "f92672" },
        { token: "delimiter", foreground: "f8f8f2" },
        { token: "tag", foreground: "f92672" },
        { token: "attribute.name", foreground: "a6e22e" },
        { token: "attribute.value", foreground: "e6db74" },
      ],
      colors: {
        "editor.background": "#272822",
        "editor.foreground": "#f8f8f2",
        "editorLineNumber.foreground": "#90908a",
        "editorLineNumber.activeForeground": "#f8f8f2",
        "editorCursor.foreground": "#f8f8f0",
        "editor.selectionBackground": "#49483e",
        "editor.inactiveSelectionBackground": "#49483e80",
        "editorIndentGuide.background1": "#464741",
        "editorIndentGuide.activeBackground1": "#767771",
        "editor.lineHighlightBackground": "#3e3d32",
        "editorBracketMatch.background": "#49483e",
        "editorBracketMatch.border": "#75715e",
      },
    },
  },
  "Monokai Pro": {
    name: "monokai-pro",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "2d2a2e", foreground: "fcfcfa" },
        { token: "keyword", foreground: "ff6188" },
        { token: "keyword.control", foreground: "ff6188" },
        { token: "type", foreground: "78dce8", fontStyle: "italic" },
        { token: "type.identifier", foreground: "a9dc76" },
        { token: "string", foreground: "ffd866" },
        { token: "string.escape", foreground: "ab9df2" },
        { token: "comment", foreground: "727072", fontStyle: "italic" },
        { token: "function", foreground: "a9dc76" },
        { token: "variable", foreground: "fcfcfa" },
        { token: "variable.parameter", foreground: "fc9867", fontStyle: "italic" },
        { token: "number", foreground: "ab9df2" },
        { token: "constant", foreground: "ab9df2" },
        { token: "operator", foreground: "ff6188" },
        { token: "delimiter", foreground: "939293" },
        { token: "tag", foreground: "ff6188" },
        { token: "attribute.name", foreground: "78dce8" },
        { token: "attribute.value", foreground: "ffd866" },
      ],
      colors: {
        "editor.background": "#2d2a2e",
        "editor.foreground": "#fcfcfa",
        "editorLineNumber.foreground": "#5b595c",
        "editorLineNumber.activeForeground": "#c1c0c0",
        "editorCursor.foreground": "#fcfcfa",
        "editor.selectionBackground": "#5b595c80",
        "editor.inactiveSelectionBackground": "#5b595c40",
        "editorIndentGuide.background1": "#403e41",
        "editorIndentGuide.activeBackground1": "#5b595c",
        "editor.lineHighlightBackground": "#363337",
        "editorBracketMatch.background": "#5b595c80",
        "editorBracketMatch.border": "#ffd866",
      },
    },
  },

  // ===========================================================================
  // Darcula (JetBrains)
  // ===========================================================================
  Darcula: {
    name: "darcula",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "2b2b2b", foreground: "a9b7c6" },
        { token: "keyword", foreground: "cc7832" },
        { token: "keyword.control", foreground: "cc7832" },
        { token: "type", foreground: "ffc66d" },
        { token: "type.identifier", foreground: "a9b7c6" },
        { token: "string", foreground: "6a8759" },
        { token: "string.escape", foreground: "cc7832" },
        { token: "comment", foreground: "808080", fontStyle: "italic" },
        { token: "function", foreground: "ffc66d" },
        { token: "variable", foreground: "a9b7c6" },
        { token: "variable.parameter", foreground: "a9b7c6" },
        { token: "number", foreground: "6897bb" },
        { token: "constant", foreground: "9876aa" },
        { token: "operator", foreground: "a9b7c6" },
        { token: "delimiter", foreground: "a9b7c6" },
        { token: "tag", foreground: "e8bf6a" },
        { token: "attribute.name", foreground: "bababa" },
        { token: "attribute.value", foreground: "a5c261" },
      ],
      colors: {
        "editor.background": "#2b2b2b",
        "editor.foreground": "#a9b7c6",
        "editorLineNumber.foreground": "#606366",
        "editorLineNumber.activeForeground": "#a4a3a3",
        "editorCursor.foreground": "#bbbbbb",
        "editor.selectionBackground": "#214283",
        "editor.inactiveSelectionBackground": "#214283aa",
        "editorIndentGuide.background1": "#3b3b3b",
        "editorIndentGuide.activeBackground1": "#4a4a4a",
        "editor.lineHighlightBackground": "#323232",
        "editorBracketMatch.background": "#3b514d",
        "editorBracketMatch.border": "#3b514d",
      },
    },
  },

  // ===========================================================================
  // Bearded Themes
  // ===========================================================================
  "Bearded Arc": {
    name: "bearded-arc",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "1c2433", foreground: "8196b5" },
        { token: "keyword", foreground: "eacd61" },
        { token: "keyword.control", foreground: "eacd61" },
        { token: "type", foreground: "b78aff" },
        { token: "type.identifier", foreground: "a4ef58" },
        { token: "string", foreground: "3cec85" },
        { token: "string.escape", foreground: "ff955c" },
        { token: "comment", foreground: "4a5567", fontStyle: "italic" },
        { token: "function", foreground: "69c3ff" },
        { token: "variable", foreground: "ff738a" },
        { token: "variable.parameter", foreground: "f38cec" },
        { token: "number", foreground: "e35535" },
        { token: "constant", foreground: "e35535" },
        { token: "operator", foreground: "eacd61" },
        { token: "delimiter", foreground: "5a6a80" },
        { token: "tag", foreground: "69c3ff" },
        { token: "attribute.name", foreground: "eacd61" },
        { token: "attribute.value", foreground: "3cec85" },
      ],
      colors: {
        "editor.background": "#1c2433",
        "editor.foreground": "#8196b5",
        "editorLineNumber.foreground": "#3b4858",
        "editorLineNumber.activeForeground": "#8196b5",
        "editorCursor.foreground": "#eacd61",
        "editor.selectionBackground": "#8196b530",
        "editor.inactiveSelectionBackground": "#8196b520",
        "editorIndentGuide.background1": "#2a3545",
        "editorIndentGuide.activeBackground1": "#3b4858",
        "editor.lineHighlightBackground": "#1f2838",
        "editorBracketMatch.background": "#8196b530",
        "editorBracketMatch.border": "#eacd61",
      },
    },
  },
  "Bearded Anthracite": {
    name: "bearded-anthracite",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "181a1f", foreground: "a2abb6" },
        { token: "keyword", foreground: "c9a022" },
        { token: "keyword.control", foreground: "c9a022" },
        { token: "type", foreground: "935cd1" },
        { token: "type.identifier", foreground: "7e9e2d" },
        { token: "string", foreground: "37ae6f" },
        { token: "string.escape", foreground: "d26d32" },
        { token: "comment", foreground: "505860", fontStyle: "italic" },
        { token: "function", foreground: "3398db" },
        { token: "variable", foreground: "de456b" },
        { token: "variable.parameter", foreground: "cc71bc" },
        { token: "number", foreground: "c13838" },
        { token: "constant", foreground: "c13838" },
        { token: "operator", foreground: "c9a022" },
        { token: "delimiter", foreground: "6a727d" },
        { token: "tag", foreground: "3398db" },
        { token: "attribute.name", foreground: "c9a022" },
        { token: "attribute.value", foreground: "37ae6f" },
      ],
      colors: {
        "editor.background": "#181a1f",
        "editor.foreground": "#a2abb6",
        "editorLineNumber.foreground": "#3b4048",
        "editorLineNumber.activeForeground": "#a2abb6",
        "editorCursor.foreground": "#c9a022",
        "editor.selectionBackground": "#a2abb630",
        "editor.inactiveSelectionBackground": "#a2abb620",
        "editorIndentGuide.background1": "#252830",
        "editorIndentGuide.activeBackground1": "#3b4048",
        "editor.lineHighlightBackground": "#1d2025",
        "editorBracketMatch.background": "#a2abb630",
        "editorBracketMatch.border": "#c9a022",
      },
    },
  },
  "Bearded Oceanic": {
    name: "bearded-oceanic",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "1b2b34", foreground: "c0c5ce" },
        { token: "keyword", foreground: "c594c5" },
        { token: "keyword.control", foreground: "c594c5" },
        { token: "type", foreground: "fac863" },
        { token: "type.identifier", foreground: "99c794" },
        { token: "string", foreground: "99c794" },
        { token: "string.escape", foreground: "f99157" },
        { token: "comment", foreground: "65737e", fontStyle: "italic" },
        { token: "function", foreground: "6699cc" },
        { token: "variable", foreground: "ec5f67" },
        { token: "variable.parameter", foreground: "f99157" },
        { token: "number", foreground: "f99157" },
        { token: "constant", foreground: "f99157" },
        { token: "operator", foreground: "5fb3b3" },
        { token: "delimiter", foreground: "a7adba" },
        { token: "tag", foreground: "6699cc" },
        { token: "attribute.name", foreground: "fac863" },
        { token: "attribute.value", foreground: "99c794" },
      ],
      colors: {
        "editor.background": "#1b2b34",
        "editor.foreground": "#c0c5ce",
        "editorLineNumber.foreground": "#4f5b66",
        "editorLineNumber.activeForeground": "#c0c5ce",
        "editorCursor.foreground": "#c594c5",
        "editor.selectionBackground": "#4f5b6650",
        "editor.inactiveSelectionBackground": "#4f5b6630",
        "editorIndentGuide.background1": "#2d3d48",
        "editorIndentGuide.activeBackground1": "#4f5b66",
        "editor.lineHighlightBackground": "#232f38",
        "editorBracketMatch.background": "#4f5b6650",
        "editorBracketMatch.border": "#5fb3b3",
      },
    },
  },
  "Bearded Vivid Black": {
    name: "bearded-vivid-black",
    definition: {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "", background: "121212", foreground: "d4d4d4" },
        { token: "keyword", foreground: "ff79c6" },
        { token: "keyword.control", foreground: "ff79c6" },
        { token: "type", foreground: "8be9fd" },
        { token: "type.identifier", foreground: "50fa7b" },
        { token: "string", foreground: "f1fa8c" },
        { token: "string.escape", foreground: "ffb86c" },
        { token: "comment", foreground: "6272a4", fontStyle: "italic" },
        { token: "function", foreground: "50fa7b" },
        { token: "variable", foreground: "ff6e6e" },
        { token: "variable.parameter", foreground: "ffb86c" },
        { token: "number", foreground: "bd93f9" },
        { token: "constant", foreground: "bd93f9" },
        { token: "operator", foreground: "ff79c6" },
        { token: "delimiter", foreground: "6272a4" },
        { token: "tag", foreground: "8be9fd" },
        { token: "attribute.name", foreground: "50fa7b" },
        { token: "attribute.value", foreground: "f1fa8c" },
      ],
      colors: {
        "editor.background": "#121212",
        "editor.foreground": "#d4d4d4",
        "editorLineNumber.foreground": "#3b3b3b",
        "editorLineNumber.activeForeground": "#d4d4d4",
        "editorCursor.foreground": "#ff79c6",
        "editor.selectionBackground": "#6272a450",
        "editor.inactiveSelectionBackground": "#6272a430",
        "editorIndentGuide.background1": "#2a2a2a",
        "editorIndentGuide.activeBackground1": "#3b3b3b",
        "editor.lineHighlightBackground": "#1a1a1a",
        "editorBracketMatch.background": "#6272a450",
        "editorBracketMatch.border": "#50fa7b",
      },
    },
  },
};

export type CodeEditorThemeName = keyof typeof EditorThemes;

export const CodeEditorThemeNames: CodeEditorThemeName[] = Object.keys(EditorThemes);

export function getCodeEditorThemeDefinition(
  themeName: CodeEditorThemeName
): monaco.editor.IStandaloneThemeData {
  return EditorThemes[themeName].definition;
}

export function getMonacoThemeName(displayName: CodeEditorThemeName): string {
  return EditorThemes[displayName]?.name ?? "vs-dark";
}

export function registerCodeEditorThemes() {
  for (const theme of Object.values(EditorThemes)) {
    monaco.editor.defineTheme(theme.name, theme.definition);
  }
}
