import { createHighlighterCore, ThemeRegistrationRaw } from "@shikijs/core";
import { createJavaScriptRegexEngine } from "@shikijs/engine-javascript";
import { shikiToMonaco } from "@shikijs/monaco";
import * as monaco from "monaco-editor-core";

export async function registerMonaco(): Promise<void> {
  const themes = Object.values(MonacoEditorThemes);

  // Create the highlighter with all registered themes
  const highlighter = await createHighlighterCore({
    themes,
    langs: [
      import("@shikijs/langs/typescript"),
      import("@shikijs/langs/javascript"),
      import("@shikijs/langs/css"),
      import("@shikijs/langs/scss"),
    ],
    engine: createJavaScriptRegexEngine(),
  });

  // Register the languageIds first. Only registered languages will be highlighted.
  monaco.languages.register({ id: "typescript" });
  monaco.languages.register({ id: "javascript" });
  monaco.languages.register({ id: "scss" });
  monaco.languages.register({ id: "css" });

  // Register the themes from Shiki, and provide syntax highlighting for Monaco.
  shikiToMonaco(highlighter, monaco);
}

export const MonacoEditorThemes: Record<string, ThemeRegistrationRaw> = {
  // ===========================================================================
  // Invert IDE App Themes
  // ===========================================================================
  "Invert Dark": {
    name: "invert-dark",
    type: "dark",
    settings: [
      { settings: { foreground: "#f0f0f0", background: "#0a0a0c" } },
      { scope: "keyword", settings: { foreground: "#da70d6", fontStyle: "bold" } },
      { scope: "keyword.control", settings: { foreground: "#da70d6" } },
      { scope: "type", settings: { foreground: "#4ec9b0" } },
      { scope: "type.identifier", settings: { foreground: "#4ec9b0" } },
      { scope: "string", settings: { foreground: "#ce9178" } },
      { scope: "string.escape", settings: { foreground: "#ffba00" } },
      { scope: "comment", settings: { foreground: "#808080", fontStyle: "italic" } },
      { scope: "function", settings: { foreground: "#dcdcaa" } },
      { scope: "variable", settings: { foreground: "#9cdcfe" } },
      { scope: "variable.parameter", settings: { foreground: "#9cdcfe" } },
      { scope: "number", settings: { foreground: "#b5cea8" } },
      { scope: "constant", settings: { foreground: "#569cd6" } },
      { scope: "operator", settings: { foreground: "#f0f0f0" } },
      { scope: "delimiter", settings: { foreground: "#808080" } },
      { scope: "tag", settings: { foreground: "#569cd6" } },
      { scope: "attribute.name", settings: { foreground: "#9cdcfe" } },
      { scope: "attribute.value", settings: { foreground: "#ce9178" } },
    ],
    colors: {
      "editor.background": "#0a0a0c",
      "editor.foreground": "#f0f0f0",
      "editorLineNumber.foreground": "#808080",
      "editorLineNumber.activeForeground": "#f0f0f0",
      "editorCursor.foreground": "#ffba00",
      "editor.selectionBackground": "#1868c466",
      "editor.inactiveSelectionBackground": "#1868c433",
      "editorIndentGuide.background1": "#2d2d2d",
      "editorIndentGuide.activeBackground1": "#808080",
      "editor.lineHighlightBackground": "#1e1e1e",
      "editorBracketMatch.background": "#1868c433",
      "editorBracketMatch.border": "#1868c4",
    },
  },

  // ===========================================================================
  // Visual Studio Code Themes
  // ===========================================================================
  "VS Code Dark": {
    name: "vscode-dark",
    type: "dark",
    settings: [
      { settings: { foreground: "#d4d4d4", background: "#1e1e1e" } },
      { scope: "keyword", settings: { foreground: "#569cd6" } },
      { scope: "keyword.control", settings: { foreground: "#c586c0" } },
      { scope: "type", settings: { foreground: "#4ec9b0" } },
      { scope: "string", settings: { foreground: "#ce9178" } },
      { scope: "comment", settings: { foreground: "#6a9955", fontStyle: "italic" } },
      { scope: "function", settings: { foreground: "#dcdcaa" } },
      { scope: "variable", settings: { foreground: "#9cdcfe" } },
      { scope: "number", settings: { foreground: "#b5cea8" } },
      { scope: "constant", settings: { foreground: "#4fc1ff" } },
      { scope: "operator", settings: { foreground: "#d4d4d4" } },
      { scope: "delimiter", settings: { foreground: "#808080" } },
    ],
    colors: {
      "checkbox.border": "#6B6B6B",
      "editor.background": "#1E1E1E",
      "editor.foreground": "#D4D4D4",
      "editor.inactiveSelectionBackground": "#3A3D41",
      "editorIndentGuide.background1": "#404040",
      "editorIndentGuide.activeBackground1": "#707070",
      "editor.selectionHighlightBackground": "#ADD6FF26",
      "list.dropBackground": "#383B3D",
      "activityBarBadge.background": "#007ACC",
      "sideBarTitle.foreground": "#BBBBBB",
      "input.placeholderForeground": "#A6A6A6",
      "menu.background": "#252526",
      "menu.foreground": "#CCCCCC",
      "menu.separatorBackground": "#454545",
      "menu.border": "#454545",
      "menu.selectionBackground": "#0078d4",
      "statusBarItem.remoteForeground": "#FFF",
      "statusBarItem.remoteBackground": "#16825D",
      "ports.iconRunningProcessForeground": "#369432",
      "sideBarSectionHeader.background": "#0000",
      "sideBarSectionHeader.border": "#ccc3",
      "tab.selectedBackground": "#222222",
      "tab.selectedForeground": "#ffffffa0",
      "tab.lastPinnedBorder": "#ccc3",
      "list.activeSelectionIconForeground": "#FFF",
      "terminal.inactiveSelectionBackground": "#3A3D41",
      "widget.border": "#303031",
      "actionBar.toggledBackground": "#383a49",
    },
  },
  "VS Code Dark+": {
    name: "vscode-dark-plus",
    type: "dark",
    settings: [
      { settings: { foreground: "#d4d4d4", background: "#1e1e1e" } },
      { scope: "keyword", settings: { foreground: "#569cd6", fontStyle: "bold" } },
      { scope: "keyword.control", settings: { foreground: "#c586c0" } },
      { scope: "type", settings: { foreground: "#4ec9b0" } },
      { scope: "type.identifier", settings: { foreground: "#4ec9b0" } },
      { scope: "string", settings: { foreground: "#ce9178" } },
      { scope: "string.escape", settings: { foreground: "#d7ba7d" } },
      { scope: "comment", settings: { foreground: "#6a9955", fontStyle: "italic" } },
      { scope: "function", settings: { foreground: "#dcdcaa" } },
      { scope: "variable", settings: { foreground: "#9cdcfe" } },
      { scope: "variable.parameter", settings: { foreground: "#9cdcfe" } },
      { scope: "number", settings: { foreground: "#b5cea8" } },
      { scope: "constant", settings: { foreground: "#4fc1ff" } },
      { scope: "operator", settings: { foreground: "#d4d4d4" } },
      { scope: "delimiter", settings: { foreground: "#808080" } },
      { scope: "tag", settings: { foreground: "#569cd6" } },
      { scope: "attribute.name", settings: { foreground: "#9cdcfe" } },
      { scope: "attribute.value", settings: { foreground: "#ce9178" } },
    ],
    colors: {
      "editor.background": "#1e1e1e",
      "editor.foreground": "#d4d4d4",
      "editorLineNumber.foreground": "#858585",
      "editorLineNumber.activeForeground": "#c6c6c6",
      "editorCursor.foreground": "#aeafad",
      "editor.selectionBackground": "#264f78",
      "editor.inactiveSelectionBackground": "#3a3d41",
      "editorIndentGuide.background1": "#404040",
      "editorIndentGuide.activeBackground1": "#707070",
      "editor.lineHighlightBackground": "#2a2d2e",
      "editorBracketMatch.background": "#0064001a",
      "editorBracketMatch.border": "#888888",
    },
  },
  "VS Code Dark Modern": {
    name: "vscode-dark-modern",
    type: "dark",
    settings: [
      { settings: { foreground: "#cccccc", background: "#1f1f1f" } },
      { scope: "keyword", settings: { foreground: "#569cd6" } },
      { scope: "keyword.control", settings: { foreground: "#c586c0" } },
      { scope: "type", settings: { foreground: "#4ec9b0" } },
      { scope: "type.identifier", settings: { foreground: "#4ec9b0" } },
      { scope: "string", settings: { foreground: "#ce9178" } },
      { scope: "string.escape", settings: { foreground: "#d7ba7d" } },
      { scope: "comment", settings: { foreground: "#6a9955", fontStyle: "italic" } },
      { scope: "function", settings: { foreground: "#dcdcaa" } },
      { scope: "variable", settings: { foreground: "#9cdcfe" } },
      { scope: "variable.parameter", settings: { foreground: "#9cdcfe" } },
      { scope: "number", settings: { foreground: "#b5cea8" } },
      { scope: "constant", settings: { foreground: "#4fc1ff" } },
      { scope: "operator", settings: { foreground: "#cccccc" } },
      { scope: "delimiter", settings: { foreground: "#808080" } },
      { scope: "tag", settings: { foreground: "#569cd6" } },
      { scope: "attribute.name", settings: { foreground: "#9cdcfe" } },
      { scope: "attribute.value", settings: { foreground: "#ce9178" } },
    ],
    colors: {
      "activityBar.activeBorder": "#0078D4",
      "activityBar.background": "#181818",
      "activityBar.border": "#2B2B2B",
      "activityBar.foreground": "#D7D7D7",
      "activityBar.inactiveForeground": "#868686",
      "activityBarBadge.background": "#0078D4",
      "activityBarBadge.foreground": "#FFFFFF",
      "badge.background": "#616161",
      "badge.foreground": "#F8F8F8",
      "button.background": "#0078D4",
      "button.border": "#ffffff1a",
      "button.foreground": "#FFFFFF",
      "button.hoverBackground": "#026EC1",
      "button.secondaryBackground": "#00000000",
      "button.secondaryForeground": "#CCCCCC",
      "button.secondaryHoverBackground": "#2B2B2B",
      "chat.slashCommandBackground": "#26477866",
      "chat.slashCommandForeground": "#85B6FF",
      "chat.editedFileForeground": "#E2C08D",
      "checkbox.background": "#313131",
      "checkbox.border": "#3C3C3C",
      "debugToolBar.background": "#181818",
      descriptionForeground: "#9D9D9D",
      "dropdown.background": "#313131",
      "dropdown.border": "#3C3C3C",
      "dropdown.foreground": "#CCCCCC",
      "dropdown.listBackground": "#1F1F1F",
      "editor.background": "#1F1F1F",
      "editor.findMatchBackground": "#9E6A03",
      "editor.foreground": "#CCCCCC",
      "editorGroup.border": "#FFFFFF17",
      "editorGroupHeader.tabsBackground": "#181818",
      "editorGroupHeader.tabsBorder": "#2B2B2B",
      "editorGutter.addedBackground": "#2EA043",
      "editorGutter.deletedBackground": "#F85149",
      "editorGutter.modifiedBackground": "#0078D4",
      "editorLineNumber.activeForeground": "#CCCCCC",
      "editorLineNumber.foreground": "#6E7681",
      "editorOverviewRuler.border": "#010409",
      "editorWidget.background": "#202020",
      errorForeground: "#F85149",
      focusBorder: "#0078D4",
      foreground: "#CCCCCC",
      "icon.foreground": "#CCCCCC",
      "input.background": "#313131",
      "input.border": "#3C3C3C",
      "input.foreground": "#CCCCCC",
      "input.placeholderForeground": "#989898",
      "inputOption.activeBackground": "#2489DB82",
      "inputOption.activeBorder": "#2488DB",
      "keybindingLabel.foreground": "#CCCCCC",
      "menu.background": "#1F1F1F",
      "menu.selectionBackground": "#0078d4",
      "notificationCenterHeader.background": "#1F1F1F",
      "notificationCenterHeader.foreground": "#CCCCCC",
      "notifications.background": "#1F1F1F",
      "notifications.border": "#2B2B2B",
      "notifications.foreground": "#CCCCCC",
      "panel.background": "#181818",
      "panel.border": "#2B2B2B",
      "panelInput.border": "#2B2B2B",
      "panelTitle.activeBorder": "#0078D4",
      "panelTitle.activeForeground": "#CCCCCC",
      "panelTitle.inactiveForeground": "#9D9D9D",
      "peekViewEditor.background": "#1F1F1F",
      "peekViewEditor.matchHighlightBackground": "#BB800966",
      "peekViewResult.background": "#1F1F1F",
      "peekViewResult.matchHighlightBackground": "#BB800966",
      "pickerGroup.border": "#3C3C3C",
      "progressBar.background": "#0078D4",
      "quickInput.background": "#222222",
      "quickInput.foreground": "#CCCCCC",
      "settings.dropdownBackground": "#313131",
      "settings.dropdownBorder": "#3C3C3C",
      "settings.headerForeground": "#FFFFFF",
      "settings.modifiedItemIndicator": "#BB800966",
      "sideBar.background": "#181818",
      "sideBar.border": "#2B2B2B",
      "sideBar.foreground": "#CCCCCC",
      "sideBarSectionHeader.background": "#181818",
      "sideBarSectionHeader.border": "#2B2B2B",
      "sideBarSectionHeader.foreground": "#CCCCCC",
      "sideBarTitle.foreground": "#CCCCCC",
      "statusBar.background": "#181818",
      "statusBar.border": "#2B2B2B",
      "statusBarItem.hoverBackground": "#F1F1F133",
      "statusBarItem.hoverForeground": "#FFFFFF",
      "statusBar.debuggingBackground": "#0078D4",
      "statusBar.debuggingForeground": "#FFFFFF",
      "statusBar.focusBorder": "#0078D4",
      "statusBar.foreground": "#CCCCCC",
      "statusBar.noFolderBackground": "#1F1F1F",
      "statusBarItem.focusBorder": "#0078D4",
      "statusBarItem.prominentBackground": "#6E768166",
      "statusBarItem.remoteBackground": "#0078D4",
      "statusBarItem.remoteForeground": "#FFFFFF",
      "tab.activeBackground": "#1F1F1F",
      "tab.activeBorder": "#1F1F1F",
      "tab.activeBorderTop": "#0078D4",
      "tab.activeForeground": "#FFFFFF",
      "tab.selectedBorderTop": "#6caddf",
      "tab.border": "#2B2B2B",
      "tab.hoverBackground": "#1F1F1F",
      "tab.inactiveBackground": "#181818",
      "tab.inactiveForeground": "#9D9D9D",
      "tab.unfocusedActiveBorder": "#1F1F1F",
      "tab.unfocusedActiveBorderTop": "#2B2B2B",
      "tab.unfocusedHoverBackground": "#1F1F1F",
      "terminal.foreground": "#CCCCCC",
      "terminal.tab.activeBorder": "#0078D4",
      "textBlockQuote.background": "#2B2B2B",
      "textBlockQuote.border": "#616161",
      "textCodeBlock.background": "#2B2B2B",
      "textLink.activeForeground": "#4daafc",
      "textLink.foreground": "#4daafc",
      "textPreformat.foreground": "#D0D0D0",
      "textPreformat.background": "#3C3C3C",
      "textSeparator.foreground": "#21262D",
      "titleBar.activeBackground": "#181818",
      "titleBar.activeForeground": "#CCCCCC",
      "titleBar.border": "#2B2B2B",
      "titleBar.inactiveBackground": "#1F1F1F",
      "titleBar.inactiveForeground": "#9D9D9D",
      "welcomePage.tileBackground": "#2B2B2B",
      "welcomePage.progress.foreground": "#0078D4",
      "widget.border": "#313131",
    },
  },

  // ===========================================================================
  // Material Themes
  // ===========================================================================
  "Material Darker": {
    name: "material-darker",
    type: "dark",
    settings: [
      { settings: { foreground: "#eeffff", background: "#212121" } },
      { scope: "keyword", settings: { foreground: "#c792ea", fontStyle: "bold" } },
      { scope: "keyword.control", settings: { foreground: "#c792ea" } },
      { scope: "type", settings: { foreground: "#ffcb6b" } },
      { scope: "type.identifier", settings: { foreground: "#ffcb6b" } },
      { scope: "string", settings: { foreground: "#c3e88d" } },
      { scope: "string.escape", settings: { foreground: "#89ddff" } },
      { scope: "comment", settings: { foreground: "#545454", fontStyle: "italic" } },
      { scope: "function", settings: { foreground: "#82aaff" } },
      { scope: "variable", settings: { foreground: "#eeffff" } },
      { scope: "variable.parameter", settings: { foreground: "#f78c6c" } },
      { scope: "number", settings: { foreground: "#f78c6c" } },
      { scope: "constant", settings: { foreground: "#f78c6c" } },
      { scope: "operator", settings: { foreground: "#89ddff" } },
      { scope: "delimiter", settings: { foreground: "#89ddff" } },
      { scope: "tag", settings: { foreground: "#f07178" } },
      { scope: "attribute.name", settings: { foreground: "#ffcb6b" } },
      { scope: "attribute.value", settings: { foreground: "#c3e88d" } },
    ],
    colors: {
      "editor.background": "#212121",
      "editor.foreground": "#eeffff",
      "editorLineNumber.foreground": "#424242",
      "editorLineNumber.activeForeground": "#89ddff",
      "editorCursor.foreground": "#ffcc00",
      "editor.selectionBackground": "#61616150",
      "editor.inactiveSelectionBackground": "#42424240",
      "editorIndentGuide.background1": "#424242",
      "editorIndentGuide.activeBackground1": "#616161",
      "editor.lineHighlightBackground": "#2a2a2a",
      "editorBracketMatch.background": "#61616150",
      "editorBracketMatch.border": "#ffcc00",
    },
  },

  // ===========================================================================
  // GitHub Themes
  // ===========================================================================
  "GitHub Dark": {
    name: "github-dark",
    type: "dark",
    settings: [
      { settings: { foreground: "#c9d1d9", background: "#0d1117" } },
      { scope: "keyword", settings: { foreground: "#ff7b72" } },
      { scope: "keyword.control", settings: { foreground: "#ff7b72" } },
      { scope: "type", settings: { foreground: "#ffa657" } },
      { scope: "type.identifier", settings: { foreground: "#ffa657" } },
      { scope: "string", settings: { foreground: "#a5d6ff" } },
      { scope: "string.escape", settings: { foreground: "#79c0ff" } },
      { scope: "comment", settings: { foreground: "#8b949e", fontStyle: "italic" } },
      { scope: "function", settings: { foreground: "#d2a8ff" } },
      { scope: "variable", settings: { foreground: "#c9d1d9" } },
      { scope: "variable.parameter", settings: { foreground: "#ffa657" } },
      { scope: "number", settings: { foreground: "#79c0ff" } },
      { scope: "constant", settings: { foreground: "#79c0ff" } },
      { scope: "operator", settings: { foreground: "#ff7b72" } },
      { scope: "delimiter", settings: { foreground: "#c9d1d9" } },
      { scope: "tag", settings: { foreground: "#7ee787" } },
      { scope: "attribute.name", settings: { foreground: "#79c0ff" } },
      { scope: "attribute.value", settings: { foreground: "#a5d6ff" } },
    ],
    colors: {
      "editor.background": "#0d1117",
      "editor.foreground": "#c9d1d9",
      "editorLineNumber.foreground": "#6e7681",
      "editorLineNumber.activeForeground": "#c9d1d9",
      "editorCursor.foreground": "#58a6ff",
      "editor.selectionBackground": "#264f7866",
      "editor.inactiveSelectionBackground": "#264f7844",
      "editorIndentGuide.background1": "#21262d",
      "editorIndentGuide.activeBackground1": "#30363d",
      "editor.lineHighlightBackground": "#161b22",
      "editorBracketMatch.background": "#264f7866",
      "editorBracketMatch.border": "#58a6ff",
    },
  },
  "GitHub Dark Dimmed": {
    name: "github-dark-dimmed",
    type: "dark",
    settings: [
      { settings: { foreground: "#adbac7", background: "#22272e" } },
      { scope: "keyword", settings: { foreground: "#f47067" } },
      { scope: "keyword.control", settings: { foreground: "#f47067" } },
      { scope: "type", settings: { foreground: "#f69d50" } },
      { scope: "type.identifier", settings: { foreground: "#f69d50" } },
      { scope: "string", settings: { foreground: "#96d0ff" } },
      { scope: "string.escape", settings: { foreground: "#6cb6ff" } },
      { scope: "comment", settings: { foreground: "#768390", fontStyle: "italic" } },
      { scope: "function", settings: { foreground: "#dcbdfb" } },
      { scope: "variable", settings: { foreground: "#adbac7" } },
      { scope: "variable.parameter", settings: { foreground: "#f69d50" } },
      { scope: "number", settings: { foreground: "#6cb6ff" } },
      { scope: "constant", settings: { foreground: "#6cb6ff" } },
      { scope: "operator", settings: { foreground: "#f47067" } },
      { scope: "delimiter", settings: { foreground: "#adbac7" } },
      { scope: "tag", settings: { foreground: "#8ddb8c" } },
      { scope: "attribute.name", settings: { foreground: "#6cb6ff" } },
      { scope: "attribute.value", settings: { foreground: "#96d0ff" } },
    ],
    colors: {
      "editor.background": "#22272e",
      "editor.foreground": "#adbac7",
      "editorLineNumber.foreground": "#636e7b",
      "editorLineNumber.activeForeground": "#adbac7",
      "editorCursor.foreground": "#539bf5",
      "editor.selectionBackground": "#3d6b9866",
      "editor.inactiveSelectionBackground": "#3d6b9844",
      "editorIndentGuide.background1": "#2d333b",
      "editorIndentGuide.activeBackground1": "#373e47",
      "editor.lineHighlightBackground": "#2d333b",
      "editorBracketMatch.background": "#3d6b9866",
      "editorBracketMatch.border": "#539bf5",
    },
  },

  // ===========================================================================
  // Monokai
  // ===========================================================================
  Monokai: {
    name: "monokai",
    type: "dark",
    settings: [
      { settings: { foreground: "#f8f8f2", background: "#272822" } },
      { scope: "keyword", settings: { foreground: "#f92672" } },
      { scope: "keyword.control", settings: { foreground: "#f92672" } },
      { scope: "type", settings: { foreground: "#66d9ef", fontStyle: "italic" } },
      { scope: "type.identifier", settings: { foreground: "#a6e22e" } },
      { scope: "string", settings: { foreground: "#e6db74" } },
      { scope: "string.escape", settings: { foreground: "#ae81ff" } },
      { scope: "comment", settings: { foreground: "#88846f", fontStyle: "italic" } },
      { scope: "function", settings: { foreground: "#a6e22e" } },
      { scope: "variable", settings: { foreground: "#f8f8f2" } },
      { scope: "variable.parameter", settings: { foreground: "#fd971f", fontStyle: "italic" } },
      { scope: "number", settings: { foreground: "#ae81ff" } },
      { scope: "constant", settings: { foreground: "#ae81ff" } },
      { scope: "operator", settings: { foreground: "#f92672" } },
      { scope: "delimiter", settings: { foreground: "#f8f8f2" } },
      { scope: "tag", settings: { foreground: "#f92672" } },
      { scope: "attribute.name", settings: { foreground: "#a6e22e" } },
      { scope: "attribute.value", settings: { foreground: "#e6db74" } },
    ],
    colors: {
      "editor.background": "#272822",
      "editor.foreground": "#f8f8f2",
      "editorLineNumber.foreground": "#90908a",
      "editorLineNumber.activeForeground": "#f8f8f2",
      "editorCursor.foreground": "#f8f8f0",
      "editor.selectionBackground": "#49483e",
      "editor.inactiveSelectionBackground": "#49483e80",
      "editorIndentGuide.background1": "#464741",
      "editorIndentGuide.activeBackground1": "#767771",
      "editor.lineHighlightBackground": "#3e3d32",
      "editorBracketMatch.background": "#49483e",
      "editorBracketMatch.border": "#75715e",
    },
  },
  "Monokai Pro": {
    name: "monokai-pro",
    type: "dark",
    settings: [
      { settings: { foreground: "#fcfcfa", background: "#2d2a2e" } },
      { scope: "keyword", settings: { foreground: "#ff6188" } },
      { scope: "keyword.control", settings: { foreground: "#ff6188" } },
      { scope: "type", settings: { foreground: "#78dce8", fontStyle: "italic" } },
      { scope: "type.identifier", settings: { foreground: "#a9dc76" } },
      { scope: "string", settings: { foreground: "#ffd866" } },
      { scope: "string.escape", settings: { foreground: "#ab9df2" } },
      { scope: "comment", settings: { foreground: "#727072", fontStyle: "italic" } },
      { scope: "function", settings: { foreground: "#a9dc76" } },
      { scope: "variable", settings: { foreground: "#fcfcfa" } },
      { scope: "variable.parameter", settings: { foreground: "#fc9867", fontStyle: "italic" } },
      { scope: "number", settings: { foreground: "#ab9df2" } },
      { scope: "constant", settings: { foreground: "#ab9df2" } },
      { scope: "operator", settings: { foreground: "#ff6188" } },
      { scope: "delimiter", settings: { foreground: "#939293" } },
      { scope: "tag", settings: { foreground: "#ff6188" } },
      { scope: "attribute.name", settings: { foreground: "#78dce8" } },
      { scope: "attribute.value", settings: { foreground: "#ffd866" } },
    ],
    colors: {
      "editor.background": "#2d2a2e",
      "editor.foreground": "#fcfcfa",
      "editorLineNumber.foreground": "#5b595c",
      "editorLineNumber.activeForeground": "#c1c0c0",
      "editorCursor.foreground": "#fcfcfa",
      "editor.selectionBackground": "#5b595c80",
      "editor.inactiveSelectionBackground": "#5b595c40",
      "editorIndentGuide.background1": "#403e41",
      "editorIndentGuide.activeBackground1": "#5b595c",
      "editor.lineHighlightBackground": "#363337",
      "editorBracketMatch.background": "#5b595c80",
      "editorBracketMatch.border": "#ffd866",
    },
  },

  // ===========================================================================
  // Bearded Themes
  // ===========================================================================
  "Bearded Arc": {
    name: "bearded-arc",
    type: "dark",
    settings: [
      { settings: { foreground: "#8196b5", background: "#1c2433" } },
      { scope: "keyword", settings: { foreground: "#eacd61" } },
      { scope: "keyword.control", settings: { foreground: "#eacd61" } },
      { scope: "type", settings: { foreground: "#b78aff" } },
      { scope: "type.identifier", settings: { foreground: "#a4ef58" } },
      { scope: "string", settings: { foreground: "#3cec85" } },
      { scope: "string.escape", settings: { foreground: "#ff955c" } },
      { scope: "comment", settings: { foreground: "#4a5567", fontStyle: "italic" } },
      { scope: "function", settings: { foreground: "#69c3ff" } },
      { scope: "variable", settings: { foreground: "#ff738a" } },
      { scope: "variable.parameter", settings: { foreground: "#f38cec" } },
      { scope: "number", settings: { foreground: "#e35535" } },
      { scope: "constant", settings: { foreground: "#e35535" } },
      { scope: "operator", settings: { foreground: "#eacd61" } },
      { scope: "delimiter", settings: { foreground: "#5a6a80" } },
      { scope: "tag", settings: { foreground: "#69c3ff" } },
      { scope: "attribute.name", settings: { foreground: "#eacd61" } },
      { scope: "attribute.value", settings: { foreground: "#3cec85" } },
    ],
    colors: {
      "editor.background": "#1c2433",
      "editor.foreground": "#8196b5",
      "editorLineNumber.foreground": "#3b4858",
      "editorLineNumber.activeForeground": "#8196b5",
      "editorCursor.foreground": "#eacd61",
      "editor.selectionBackground": "#8196b530",
      "editor.inactiveSelectionBackground": "#8196b520",
      "editorIndentGuide.background1": "#2a3545",
      "editorIndentGuide.activeBackground1": "#3b4858",
      "editor.lineHighlightBackground": "#1f2838",
      "editorBracketMatch.background": "#8196b530",
      "editorBracketMatch.border": "#eacd61",
    },
  },
  "Bearded Anthracite": {
    name: "bearded-anthracite",
    type: "dark",
    settings: [
      { settings: { foreground: "#a2abb6", background: "#181a1f" } },
      { scope: "keyword", settings: { foreground: "#c9a022" } },
      { scope: "keyword.control", settings: { foreground: "#c9a022" } },
      { scope: "type", settings: { foreground: "#935cd1" } },
      { scope: "type.identifier", settings: { foreground: "#7e9e2d" } },
      { scope: "string", settings: { foreground: "#37ae6f" } },
      { scope: "string.escape", settings: { foreground: "#d26d32" } },
      { scope: "comment", settings: { foreground: "#505860", fontStyle: "italic" } },
      { scope: "function", settings: { foreground: "#3398db" } },
      { scope: "variable", settings: { foreground: "#de456b" } },
      { scope: "variable.parameter", settings: { foreground: "#cc71bc" } },
      { scope: "number", settings: { foreground: "#c13838" } },
      { scope: "constant", settings: { foreground: "#c13838" } },
      { scope: "operator", settings: { foreground: "#c9a022" } },
      { scope: "delimiter", settings: { foreground: "#6a727d" } },
      { scope: "tag", settings: { foreground: "#3398db" } },
      { scope: "attribute.name", settings: { foreground: "#c9a022" } },
      { scope: "attribute.value", settings: { foreground: "#37ae6f" } },
    ],
    colors: {
      "editor.background": "#181a1f",
      "editor.foreground": "#a2abb6",
      "editorLineNumber.foreground": "#3b4048",
      "editorLineNumber.activeForeground": "#a2abb6",
      "editorCursor.foreground": "#c9a022",
      "editor.selectionBackground": "#a2abb630",
      "editor.inactiveSelectionBackground": "#a2abb620",
      "editorIndentGuide.background1": "#252830",
      "editorIndentGuide.activeBackground1": "#3b4048",
      "editor.lineHighlightBackground": "#1d2025",
      "editorBracketMatch.background": "#a2abb630",
      "editorBracketMatch.border": "#c9a022",
    },
  },
  "Bearded Vivid Black": {
    name: "bearded-vivid-black",
    type: "dark",
    settings: [
      { settings: { foreground: "#d4d4d4", background: "#121212" } },
      { scope: "keyword", settings: { foreground: "#ff79c6" } },
      { scope: "keyword.control", settings: { foreground: "#ff79c6" } },
      { scope: "type", settings: { foreground: "#8be9fd" } },
      { scope: "type.identifier", settings: { foreground: "#50fa7b" } },
      { scope: "string", settings: { foreground: "#f1fa8c" } },
      { scope: "string.escape", settings: { foreground: "#ffb86c" } },
      { scope: "comment", settings: { foreground: "#6272a4", fontStyle: "italic" } },
      { scope: "function", settings: { foreground: "#50fa7b" } },
      { scope: "variable", settings: { foreground: "#ff6e6e" } },
      { scope: "variable.parameter", settings: { foreground: "#ffb86c" } },
      { scope: "number", settings: { foreground: "#bd93f9" } },
      { scope: "constant", settings: { foreground: "#bd93f9" } },
      { scope: "operator", settings: { foreground: "#ff79c6" } },
      { scope: "delimiter", settings: { foreground: "#6272a4" } },
      { scope: "tag", settings: { foreground: "#8be9fd" } },
      { scope: "attribute.name", settings: { foreground: "#50fa7b" } },
      { scope: "attribute.value", settings: { foreground: "#f1fa8c" } },
    ],
    colors: {
      "editor.background": "#121212",
      "editor.foreground": "#d4d4d4",
      "editorLineNumber.foreground": "#3b3b3b",
      "editorLineNumber.activeForeground": "#d4d4d4",
      "editorCursor.foreground": "#ff79c6",
      "editor.selectionBackground": "#6272a450",
      "editor.inactiveSelectionBackground": "#6272a430",
      "editorIndentGuide.background1": "#2a2a2a",
      "editorIndentGuide.activeBackground1": "#3b3b3b",
      "editor.lineHighlightBackground": "#1a1a1a",
      "editorBracketMatch.background": "#6272a450",
      "editorBracketMatch.border": "#50fa7b",
    },
  },

  // ===========================================================================
  // Invert IDE App Themes
  // ===========================================================================
  "Graphite Dusk": {
    name: "graphite-dusk",
    type: "dark",
    settings: [
      { settings: { foreground: "#d2d0d6", background: "#1e1d20" } },
      { scope: "keyword", settings: { foreground: "#c586c0", fontStyle: "bold" } },
      { scope: "keyword.control", settings: { foreground: "#c586c0" } },
      { scope: "type", settings: { foreground: "#4ec9b0" } },
      { scope: "type.identifier", settings: { foreground: "#4ec9b0" } },
      { scope: "string", settings: { foreground: "#ce9178" } },
      { scope: "string.escape", settings: { foreground: "#d7ba7d" } },
      { scope: "comment", settings: { foreground: "#626068", fontStyle: "italic" } },
      { scope: "function", settings: { foreground: "#dcdcaa" } },
      { scope: "variable", settings: { foreground: "#b8b4ea" } },
      { scope: "variable.parameter", settings: { foreground: "#b8b4ea" } },
      { scope: "number", settings: { foreground: "#b5cea8" } },
      { scope: "constant", settings: { foreground: "#a4a0e0" } },
      { scope: "operator", settings: { foreground: "#d2d0d6" } },
      { scope: "delimiter", settings: { foreground: "#82808a" } },
      { scope: "tag", settings: { foreground: "#a4a0e0" } },
      { scope: "attribute.name", settings: { foreground: "#b8b4ea" } },
      { scope: "attribute.value", settings: { foreground: "#ce9178" } },
    ],
    colors: {
      "editor.background": "#1e1d20",
      "editor.foreground": "#d2d0d6",
      "editorLineNumber.foreground": "#58545e",
      "editorLineNumber.activeForeground": "#d2d0d6",
      "editorCursor.foreground": "#a088c8",
      "editor.selectionBackground": "#a088c840",
      "editor.inactiveSelectionBackground": "#a088c825",
      "editorIndentGuide.background1": "#323036",
      "editorIndentGuide.activeBackground1": "#3c3a42",
      "editor.lineHighlightBackground": "#252428",
      "editorBracketMatch.background": "#a088c830",
      "editorBracketMatch.border": "#a088c8",
    },
  },
};

export function getCodeEditorThemeName(displayName: string): string {
  return MonacoEditorThemes[displayName]?.name;
}
